version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine/
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /debian/
    schedule:
      interval: daily
