queue_rules:
  - name: default
    conditions:
      - check-success=build-alpine
      - check-success=build-debian
      - check-success=build-debian-arm64

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-alpine
      - check-success=build-debian
      - check-success=build-debian-arm64
    actions:
      queue:
        method: merge
        name: default
